/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 4;
  /** RegularExpression Id. */
  int PRINT = 5;
  /** RegularExpression Id. */
  int DO = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int EQCOMP = 12;
  /** RegularExpression Id. */
  int DEREF = 13;
  /** RegularExpression Id. */
  int NEW = 14;
  /** RegularExpression Id. */
  int SEQ = 15;
  /** RegularExpression Id. */
  int DEF = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int Id = 20;
  /** RegularExpression Id. */
  int Num = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int TIMES = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int LPAR = 26;
  /** RegularExpression Id. */
  int RPAR = 27;
  /** RegularExpression Id. */
  int EL = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"println\"",
    "\"print\"",
    "\"do\"",
    "\"while\"",
    "\"else\"",
    "\"then\"",
    "\"if\"",
    "\":=\"",
    "\"==\"",
    "\"!\"",
    "\"new\"",
    "\";\"",
    "\"def\"",
    "\"in\"",
    "\"=\"",
    "\"end\"",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
  };

}
