/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 4;
  /** RegularExpression Id. */
  int PRINT = 5;
  /** RegularExpression Id. */
  int BOOL = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int EQCOMP = 13;
  /** RegularExpression Id. */
  int NOTEQ = 14;
  /** RegularExpression Id. */
  int GREAT = 15;
  /** RegularExpression Id. */
  int GREATTHAN = 16;
  /** RegularExpression Id. */
  int LESS = 17;
  /** RegularExpression Id. */
  int LESSTHAN = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int NEG = 21;
  /** RegularExpression Id. */
  int DEREF = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int SEQ = 24;
  /** RegularExpression Id. */
  int DEF = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int END = 28;
  /** RegularExpression Id. */
  int Id = 29;
  /** RegularExpression Id. */
  int Num = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int TIMES = 33;
  /** RegularExpression Id. */
  int DIV = 34;
  /** RegularExpression Id. */
  int MOD = 35;
  /** RegularExpression Id. */
  int LPAR = 36;
  /** RegularExpression Id. */
  int RPAR = 37;
  /** RegularExpression Id. */
  int EL = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"println\"",
    "\"print\"",
    "<BOOL>",
    "\"do\"",
    "\"while\"",
    "\"else\"",
    "\"then\"",
    "\"if\"",
    "\":=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"!\"",
    "\"new\"",
    "\";\"",
    "\"def\"",
    "\"in\"",
    "\"=\"",
    "\"end\"",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
  };

}
